### ISSUE TITLE
Right clicking words does not offer any download option? 

### ISSUE THREAD

**Issue by Schaffah** [Rascalov/Anki-Simple-Forvo-Audio#4] opened 2021-08-17 17:13 UTC
I'm on the newest version of the addon using Windows 10. When I right click a word, there's no option to download a word or anything. 

Is there any troubleshooting steps I can take? I'd really like to use this addon =)

**Comment by Rascalov** [comment] 2021-08-17 17:49
Thank you for your interest. It will not be taken for granted.
Sadly, https://github.com/Rascalov/Anki-Simple-Forvo-Audio/issues/2 also had this problem.
When I installed it on windows 10 myself, I had no problems. I should probably test more on clean installs, but windows is foreign territory for me.
For now, I will do a few shots in the dark.
Though unlikely, perhaps you need to install [python3](https://www.python.org/downloads/)? 

Otherwise, try this:
I am no expert in windows, but I think you can get debug information if you run anki.exe in the command prompt (command prompt as Administrator).

1. Open Command prompt as administrator
2. go to the anki folder: `cd C:/Program Files/Anki` (I think this is the path it installs anki to)
3. then paste this: `anki.exe > debugFile.txt` 
4. If anki opens, close it (otherwise the file stays empty).
5. You should have a file called debugFile.txt inside this folder.

If you could copy paste the file here, maybe there is something I recognize to be the problem.

**Comment by Schaffah** [comment] 2021-08-17 18:51
[debugFile.txt](https://github.com/Rascalov/Anki-Simple-Forvo-Audio/files/7002330/debugFile.txt)

Hi Tim,

Thanks for looking into this, very kind of you! I have posted the debufFile. If you see any glaring issues, It would be awesome to fix it. If not, I don't expect ya to spend time troubleshooting an OS you're not involved with.

Thanks again!

**Comment by Rascalov** [comment] 2021-08-17 20:29
Hmm, it seems like my addon produced no useful warnings. I see warnings for addons: `723520343` (ReviewHeatmap) and `1102281552` (Special Fields), but I doubt disabling those addons will allow mine to work (though I can't rule it out, but it would be silly if my extension forces another useful extension out).
I'll have more time in the weekends to use windows machines, I'll see if there is something I'm missing.

**Comment by Schaffah** [comment] 2021-08-17 20:50
Hi Tim,

Since you pointed out other addons may be the issue, I disabled everything and enabled them 1 by 1. Turns out, the issue was this addon: 
Image Occlusion Enhanced for Anki 2.1 (alpha) -- code 1374772155

This is one of the most popular addons, which may also explain why the other user had a problem with the addon. However, it's functionality is such that you wouldn't need it on 99% of the time, unless you are in the process of making new Image occlusion cards. 

So the easy / obvious solution is to just shut that addon off until you absolutely need it. I just tested it out, and it 100% works, inputting the sound file where I expected it. 

Thanks for your help!

**Comment by Rascalov** [comment] 2021-08-17 21:08
Thank you for the information! 
It would sad to discover that my addon forces the user to disable other extensions.
Since more popular addons tend to be more polished in terms of compatibility, it could well be a problem caused by my addon.

Nevertheless, I'll close the issue for now. Thank you for your contributions and discoveries!

**Closed by Rascalov** 2021-08-17 21:08 UTC
